# Generated by Django 5.2.1 on 2025-05-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('top_speed_kph', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('length_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tracks/')),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='race_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='league',
            name='cars',
        ),
        migrations.AlterField(
            model_name='league',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='leagues/'),
        ),
        migrations.AlterField(
            model_name='league',
            name='race_day',
            field=models.CharField(max_length=78),
        ),
        migrations.RemoveField(
            model_name='league',
            name='tracks',
        ),
        migrations.AddField(
            model_name='league',
            name='cars',
            field=models.ManyToManyField(related_name='leagues', to='leagues.car'),
        ),
        migrations.AddField(
            model_name='league',
            name='tracks',
            field=models.ManyToManyField(related_name='leagues', to='leagues.track'),
        ),
    ]
