# Generated by Django 5.2.1 on 2025-05-28 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='league',
            name='participants',
            field=models.ManyToManyField(related_name='joined_leagues', through='leagues.LeagueRegistration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='league',
            name='tracks',
            field=models.ManyToManyField(related_name='leagues', to='leagues.track'),
        ),
        migrations.AlterUniqueTogether(
            name='leagueregistration',
            unique_together={('user', 'league')},
        ),
    ]
