# Generated by Django 5.2.1 on 2025-05-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='participants',
        ),
        migrations.AddField(
            model_name='league',
            name='max_participants',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
