# Generated by Django 5.2.1 on 2025-05-21 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_car_track_league_race_time_remove_league_cars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='car',
            name='top_speed_kph',
        ),
    ]
