# Generated by Django 5.2.1 on 2025-05-21 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_remove_car_manufacturer_remove_car_top_speed_kph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='length_km',
        ),
        migrations.RemoveField(
            model_name='track',
            name='location',
        ),
    ]
