# Generated by Django 5.2.1 on 2025-06-04 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_league_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('race_date', models.DateTimeField()),
                ('laps', models.PositiveIntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('weather_conditions', models.CharField(blank=True, max_length=100)),
                ('race_length_minutes', models.PositiveIntegerField(blank=True, help_text='Race length in minutes', null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='leagues.league')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.track')),
            ],
            options={
                'ordering': ['-race_date'],
            },
        ),
        migrations.CreateModel(
            name='ChampionshipStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('races_participated', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('podiums', models.PositiveIntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='leagues.league')),
            ],
            options={
                'ordering': ['-total_points', '-wins', '-podiums'],
                'unique_together': {('league', 'driver')},
            },
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('fastest_lap_time', models.CharField(blank=True, help_text='Format: MM:SS.mmm', max_length=20)),
                ('total_time', models.CharField(blank=True, help_text='Format: HH:MM:SS.mmm', max_length=20)),
                ('laps_completed', models.PositiveIntegerField(default=0)),
                ('dnf', models.BooleanField(default=False, verbose_name='Did Not Finish')),
                ('dnf_reason', models.CharField(blank=True, max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='leagues.race')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('race', 'driver')},
            },
        ),
    ]
