# Generated by Django 5.2.1 on 2025-06-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_race_championshipstanding_raceresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='tracks',
        ),
        migrations.RemoveField(
            model_name='race',
            name='race_length_minutes',
        ),
        migrations.RemoveField(
            model_name='raceresult',
            name='dnf_reason',
        ),
        migrations.RemoveField(
            model_name='raceresult',
            name='total_time',
        ),
    ]
